export const SET_ABOUT_DATA = 'SET_ABOUT_DATA';

export const SET_FIRST_STEP_DATA = 'SET_FIRST_STEP_DATA';
export const SET_SECOND_STEP_DATA = 'SET_SECOND_STEP_DATA';
export const SET_THIRD_STEP_DATA = 'SET_THIRD_STEP_DATA';

export const SET_PART_DATA = 'SET_PART_DATA';

export const SET_NEXT_ACTIVE_STEP = 'SET_NEXT_ACTIVE_STEP';
export const SET_PREVIOUS_ACTIVE_STEP = 'SET_PREVIOUS_ACTIVE_STEP';
